<?php
/**
 * Single source of truth for the Pusat Karir schema used by diagram
 * generators (StarUML .mdj, draw.io .drawio).
 *
 * Column row: [name, type, length|null, ...flags]
 *   flags: 'pk' primary key, 'fk' foreign key, 'uk' unique, 'null' nullable
 * Relationship row: [child_table, child_column, parent_table, parent_column]
 *   (child is the N side; parent is the 1 side)
 */

return [
    'entities' => [
        'users' => [
            ['id',                'BIGINT',   null, 'pk'],
            ['first_name',        'VARCHAR',  255],
            ['last_name',         'VARCHAR',  255],
            ['email',             'VARCHAR',  255, 'uk'],
            ['phone_number',      'VARCHAR',  255, 'null'],
            ['street_addr',       'VARCHAR',  255, 'null'],
            ['email_verified_at', 'TIMESTAMP',null,'null'],
            ['user_type',         'VARCHAR',  255],
            ['password',          'VARCHAR',  255],
            ['status',            'ENUM',     null],
            ['profile_image',     'VARCHAR',  255, 'null'],
            ['remember_token',    'VARCHAR',  100, 'null'],
            ['created_at',        'TIMESTAMP',null,'null'],
            ['updated_at',        'TIMESTAMP',null,'null'],
        ],
        'social_media' => [
            ['id',                    'BIGINT',  null, 'pk'],
            ['platform_social_media', 'VARCHAR', 50],
            ['created_at',            'TIMESTAMP',null,'null'],
            ['updated_at',            'TIMESTAMP',null,'null'],
        ],
        'user_social_media' => [
            ['id',                 'BIGINT', null, 'pk'],
            ['user_id',            'BIGINT', null, 'fk'],
            ['social_media_id',    'BIGINT', null, 'fk'],
            ['social_media_name',  'VARCHAR',255],
            ['created_at',         'TIMESTAMP',null,'null'],
            ['updated_at',         'TIMESTAMP',null,'null'],
        ],
        'notification' => [
            ['id',         'BIGINT', null, 'pk'],
            ['user_id',    'BIGINT', null, 'fk'],
            ['type',       'VARCHAR',50],
            ['title',      'VARCHAR',150],
            ['message',    'TEXT',   null],
            ['link',       'VARCHAR',255, 'null'],
            ['is_read',    'BOOLEAN',null],
            ['created_at', 'TIMESTAMP',null,'null'],
            ['updated_at', 'TIMESTAMP',null,'null'],
        ],
        'industri_type' => [
            ['id',            'BIGINT', null, 'pk'],
            ['nama_industri', 'VARCHAR',50],
            ['created_at',    'TIMESTAMP',null,'null'],
            ['updated_at',    'TIMESTAMP',null,'null'],
        ],
        'employer' => [
            ['id',                  'BIGINT', null, 'pk'],
            ['user_id',             'BIGINT', null, 'fk'],
            ['industriType_id',     'BIGINT', null, 'fk'],
            ['nama_perusahaan',     'VARCHAR',50],
            ['deskripsi_perusahaan','TEXT',   null],
            ['alamat_perusahaan',   'VARCHAR',255],
            ['telp_perusahaan',     'VARCHAR',255],
            ['website',             'VARCHAR',255],
            ['created_at',          'TIMESTAMP',null,'null'],
            ['updated_at',          'TIMESTAMP',null,'null'],
        ],
        'posisi' => [
            ['id',          'BIGINT', null, 'pk'],
            ['nama_posisi', 'VARCHAR',25],
            ['created_at',  'TIMESTAMP',null,'null'],
            ['updated_at',  'TIMESTAMP',null,'null'],
        ],
        'job' => [
            ['id',                   'BIGINT', null, 'pk'],
            ['employer_id',          'BIGINT', null, 'fk'],
            ['nama_pekerjaan',       'VARCHAR',50],
            ['posisi',               'VARCHAR',255],
            ['requirement',          'TEXT',   null],
            ['deskripsi_pekerjaan',  'VARCHAR',255],
            ['alamat',               'VARCHAR',255],
            ['ekspektasi_gaji',      'VARCHAR',255],
            ['worktime',             'VARCHAR',255],
            ['application_deadline', 'DATE',   null],
            ['created_at',           'TIMESTAMP',null,'null'],
            ['updated_at',           'TIMESTAMP',null,'null'],
        ],
        '_kualifikasi_job' => [
            ['id',          'BIGINT', null, 'pk'],
            ['job_id',      'BIGINT', null, 'fk'],
            ['kualifikasi', 'VARCHAR',255],
            ['created_at',  'TIMESTAMP',null,'null'],
            ['updated_at',  'TIMESTAMP',null,'null'],
        ],
        'tugas_dan_tanggung_jawab' => [
            ['id',         'BIGINT', null, 'pk'],
            ['job_id',     'BIGINT', null, 'fk'],
            ['tugas',      'VARCHAR',255],
            ['created_at', 'TIMESTAMP',null,'null'],
            ['updated_at', 'TIMESTAMP',null,'null'],
        ],
        'proses' => [
            ['id',          'BIGINT', null, 'pk'],
            ['nama_proses', 'VARCHAR',50],
            ['created_at',  'TIMESTAMP',null,'null'],
            ['updated_at',  'TIMESTAMP',null,'null'],
        ],
        'step' => [
            ['id',         'BIGINT', null, 'pk'],
            ['job_id',     'BIGINT', null, 'fk'],
            ['proses_id',  'BIGINT', null, 'fk'],
            ['urutan',     'INTEGER',null],
            ['deskripsi',  'TEXT',   null],
            ['created_at', 'TIMESTAMP',null,'null'],
            ['updated_at', 'TIMESTAMP',null,'null'],
        ],
        'jobseeker_type' => [
            ['id',            'BIGINT', null, 'pk'],
            ['jobseekerType', 'VARCHAR',15],
            ['created_at',    'TIMESTAMP',null,'null'],
            ['updated_at',    'TIMESTAMP',null,'null'],
        ],
        'jobseeker' => [
            ['id',                'BIGINT', null, 'pk'],
            ['user_id',           'BIGINT', null, 'fk'],
            ['jobseeker_type_id', 'BIGINT', null, 'fk'],
            ['first_name',        'VARCHAR',20],
            ['last_name',         'VARCHAR',20],
            ['jenis_kelamin',     'VARCHAR',15],
            ['ttl',               'DATE',   null],
            ['created_at',        'TIMESTAMP',null,'null'],
            ['updated_at',        'TIMESTAMP',null,'null'],
        ],
        'application' => [
            ['id',            'BIGINT', null, 'pk'],
            ['jobseeker_id',  'BIGINT', null, 'fk'],
            ['job_id',        'BIGINT', null, 'fk'],
            ['tanggal_apply', 'DATE',   null],
            ['status',        'ENUM',   null],
            ['created_at',    'TIMESTAMP',null,'null'],
            ['updated_at',    'TIMESTAMP',null,'null'],
        ],
        'progress' => [
            ['id',             'BIGINT', null, 'pk'],
            ['application_id', 'BIGINT', null, 'fk'],
            ['step_id',        'BIGINT', null, 'fk'],
            ['catatan',        'TEXT',   null],
            ['lulus',          'BOOLEAN',null],
            ['created_at',     'TIMESTAMP',null,'null'],
            ['updated_at',     'TIMESTAMP',null,'null'],
        ],
        'organisasi' => [
            ['id',              'BIGINT', null, 'pk'],
            ['jobseeker_id',    'BIGINT', null, 'fk'],
            ['nama_organisasi', 'VARCHAR',30],
            ['jabatan',         'VARCHAR',20],
            ['keterangan',      'TEXT',   null],
            ['created_at',      'TIMESTAMP',null,'null'],
            ['updated_at',      'TIMESTAMP',null,'null'],
        ],
        'bahasa' => [
            ['id',           'BIGINT', null, 'pk'],
            ['jobseeker_id', 'BIGINT', null, 'fk'],
            ['bahasa',       'VARCHAR',20],
            ['keterangan',   'TEXT',   null],
            ['created_at',   'TIMESTAMP',null,'null'],
            ['updated_at',   'TIMESTAMP',null,'null'],
        ],
        'riwayat_kerja' => [
            ['id',           'BIGINT', null, 'pk'],
            ['jobseeker_id', 'BIGINT', null, 'fk'],
            ['keterangan',   'TEXT',   null],
            ['created_at',   'TIMESTAMP',null,'null'],
            ['updated_at',   'TIMESTAMP',null,'null'],
        ],
        'prestasi' => [
            ['id',                'BIGINT', null, 'pk'],
            ['jobseeker_id',      'BIGINT', null, 'fk'],
            ['nama_penghargaan',  'VARCHAR',40],
            ['tahun',             'VARCHAR',4],
            ['dokumen',           'VARCHAR',250],
            ['created_at',        'TIMESTAMP',null,'null'],
            ['updated_at',        'TIMESTAMP',null,'null'],
        ],
        'riwayat_pendidikan' => [
            ['id',           'BIGINT', null, 'pk'],
            ['jobseeker_id', 'BIGINT', null, 'fk'],
            ['jenjang',      'VARCHAR',5],
            ['instansi',     'VARCHAR',50],
            ['indeks_nilai', 'VARCHAR',4, 'null'],
            ['keterangan',   'TEXT',   null],
            ['created_at',   'TIMESTAMP',null,'null'],
            ['updated_at',   'TIMESTAMP',null,'null'],
        ],
        'pelatihan' => [
            ['id',             'BIGINT', null, 'pk'],
            ['jobseeker_id',   'BIGINT', null, 'fk'],
            ['nama_pelatihan', 'VARCHAR',50],
            ['tahun',          'VARCHAR',4],
            ['sertifikat',     'VARCHAR',250],
            ['created_at',     'TIMESTAMP',null,'null'],
            ['updated_at',     'TIMESTAMP',null,'null'],
        ],
        'rekomendasi' => [
            ['id',                 'BIGINT', null, 'pk'],
            ['jobseeker_id',       'BIGINT', null, 'fk'],
            ['nama_perekomendasi', 'VARCHAR',30],
            ['posisi',             'VARCHAR',20],
            ['no_hp',              'VARCHAR',14],
            ['alamat',             'VARCHAR',50],
            ['created_at',         'TIMESTAMP',null,'null'],
            ['updated_at',         'TIMESTAMP',null,'null'],
        ],
        'membership' => [
            ['id',              'BIGINT', null, 'pk'],
            ['nama_membership', 'VARCHAR',50],
            ['durasi',          'VARCHAR',25],
            ['harga',           'VARCHAR',50],
            ['created_at',      'TIMESTAMP',null,'null'],
            ['updated_at',      'TIMESTAMP',null,'null'],
        ],
        'account' => [
            ['nomor_rekening', 'BIGINT', null, 'pk'],
            ['nama_bank',      'VARCHAR',25],
            ['atas_nama',      'VARCHAR',35],
            ['created_at',     'TIMESTAMP',null,'null'],
            ['updated_at',     'TIMESTAMP',null,'null'],
        ],
        'pembayaran' => [
            ['id',             'BIGINT', null, 'pk'],
            ['user_id',        'BIGINT', null, 'fk'],
            ['membership_id',  'BIGINT', null, 'fk'],
            ['nomor_rekening', 'BIGINT', null, 'fk'],
            ['tgl_mulai',      'DATE',   null],
            ['tgl_berakhir',   'DATE',   null],
            ['created_at',     'TIMESTAMP',null,'null'],
            ['updated_at',     'TIMESTAMP',null,'null'],
        ],
        'job_fair' => [
            ['id',              'BIGINT', null, 'pk'],
            ['nama',            'VARCHAR',100],
            ['deskripsi',       'TEXT',   null, 'null'],
            ['lokasi',          'VARCHAR',100],
            ['tanggal_mulai',   'DATE',   null],
            ['tanggal_selesai', 'DATE',   null],
            ['status',          'ENUM',   null],
            ['created_at',      'TIMESTAMP',null,'null'],
            ['updated_at',      'TIMESTAMP',null,'null'],
        ],
        'job_fair_job' => [
            ['id',          'BIGINT', null, 'pk'],
            ['job_fair_id', 'BIGINT', null, 'fk'],
            ['job_id',      'BIGINT', null, 'fk'],
            ['employer_id', 'BIGINT', null, 'fk'],
            ['status',      'ENUM',   null],
            ['created_at',  'TIMESTAMP',null,'null'],
            ['updated_at',  'TIMESTAMP',null,'null'],
        ],
    ],

    'relationships' => [
        ['user_social_media',        'user_id',          'users',         'id'],
        ['user_social_media',        'social_media_id',  'social_media',  'id'],
        ['notification',             'user_id',          'users',         'id'],
        ['employer',                 'user_id',          'users',         'id'],
        ['employer',                 'industriType_id',  'industri_type', 'id'],
        ['job',                      'employer_id',      'employer',      'id'],
        ['_kualifikasi_job',         'job_id',           'job',           'id'],
        ['tugas_dan_tanggung_jawab', 'job_id',           'job',           'id'],
        ['step',                     'job_id',           'job',           'id'],
        ['step',                     'proses_id',        'proses',        'id'],
        ['jobseeker',                'user_id',          'users',         'id'],
        ['jobseeker',                'jobseeker_type_id','jobseeker_type','id'],
        ['application',              'jobseeker_id',     'jobseeker',     'id'],
        ['application',              'job_id',           'job',           'id'],
        ['progress',                 'application_id',   'application',   'id'],
        ['progress',                 'step_id',          'step',          'id'],
        ['organisasi',               'jobseeker_id',     'jobseeker',     'id'],
        ['bahasa',                   'jobseeker_id',     'jobseeker',     'id'],
        ['riwayat_kerja',            'jobseeker_id',     'jobseeker',     'id'],
        ['prestasi',                 'jobseeker_id',     'jobseeker',     'id'],
        ['riwayat_pendidikan',       'jobseeker_id',     'jobseeker',     'id'],
        ['pelatihan',                'jobseeker_id',     'jobseeker',     'id'],
        ['rekomendasi',              'jobseeker_id',     'jobseeker',     'id'],
        ['pembayaran',               'user_id',          'users',         'id'],
        ['pembayaran',               'membership_id',    'membership',    'id'],
        ['pembayaran',               'nomor_rekening',   'account',       'nomor_rekening'],
        ['job_fair_job',             'job_fair_id',      'job_fair',      'id'],
        ['job_fair_job',             'job_id',           'job',           'id'],
        ['job_fair_job',             'employer_id',      'employer',      'id'],
    ],
];
